### ISSUE TITLE
user_groups permission doesn't appear in the graph api explorer option

### ISSUE THREAD

**Issue by hellyeah** [kern/fb_scrape#1]
![screen shot 2015-10-20 at 10 26 19 am](https://cloud.githubusercontent.com/assets/1475361/10615505/0db5fa92-7715-11e5-8d31-3989125b455a.png)

**Comment by hellyeah** [comment]
API v2.3 or older: https://developers.facebook.com/docs/facebook-login/permissions/v2.5#reference-user_groups

**Comment by hellyeah** [comment]
Did you have to get the permission approved for the hackbot app?

**Comment by kern** [comment]
`user_managed_groups` is the new permission. :)
